services:
  camel:
    image: camel:latest
    container_name: camel
    build:
      context: ../
      dockerfile: .container/Dockerfile
    env_file:
      - .env
    command: ["tail", "-f", "/dev/null"]
